name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      variation:
        description: 'Variation'
        default: 'upgrade'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: |
        sed -i -e "s|VARIATION_NAME|${{ inputs.variation }}|g" Dockerfile

    - name: Build Images
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_SUMMARY: false
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/ietf-tools/upgrade-page:${{ inputs.variation }}
